apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: build-image
spec:
  description: This task is for building image
  params:
    - name: image-name
      description: name of the image which needs to be created
      default: "sample-image"
  results:
    - name: image-tag
      description: tag of the image

  stepTemplate:
    env:
      - name: IMAGE_NAME
        value: $(params.image-name)

  steps:
    - name: test-build-image
      image: registry.access.redhat.com/ubi9/ubi
      script: |
        #!/usr/bin/env python3
        txt = "refs/tags/1.8"
        x = txt.startswith("refs/tags/")
        print(x)
        $(results.image-tag.path) = x
        exit(0)
