apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: get-tags
spec:
  description: This task is for get commit tags
  results:
    - name: new-image-tag
      description: get git commit tag
      
  steps:
    - name: get-commit-tag
      image: registry.access.redhat.com/ubi9/ubi
      script: |
        #!/bin/bash
        echo "Executing get-tags task"
        gitTag=$(echo $(params.git-tag))
        echo $gitTag
        var="refs/tags/1.8"
        commitShortSha=$(echo $(params.revision) | head -c8)
        commitTag=""
        if [[ "$var" =~ ^"refs/tags/" ]]
            then
                IFS='\/' read -ra TAGS <<< "$var"
                commitTag="_"${TAGS[2]}
        fi
        newImageTag="${commitShortSha}${commitTag}"
        echo $newImageTag > "$(results.new-image-tag.path)"
