apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: get-git-tag
spec:
  description: This task is for get commit tags
  results:
    - name: image-tag
      description: get image tag as combination of git commit tag and short SHA
    - name: git-tag
      description: get git commit tag
      
  steps:
    - name: get-tags
      image: registry.access.redhat.com/ubi9/ubi
      script: |
        #!/bin/bash
        echo "Executing get-tags task"
        gitTag=$(echo $(params.git-refs-tag))
        echo $gitTag
        #var="refs/tags/1.8"
        commitShortSha=$(echo $(params.revision) | head -c8)
        commitTag=""
        if [[ "$gitTag" =~ ^"refs/tags/" ]]
            then
                IFS='\/' read -ra TAGS <<< "$gitTag"
                commitTag=${TAGS[2]}"_"
                echo ${TAGS[2]} > "$(results.git-tag.path)"
        fi
        imageTag="${commitTag}${commitShortSha}"
        echo $imageTag > "$(results.image-tag.path)"
