apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: get-tags
spec:
  description: This task is for get commit tags
  results:
    - name: commit-tag
      description: get git commit tag
      
  steps:
    - name: get-commit-tag
      image: registry.access.redhat.com/ubi9/ubi
      script: |
        #!/bin/bash
        echo "Executing get-tags task"
        IN="refs/tags/1.8"
        ADDRS=( $(IFS=";" echo "$IN") )
        echo ${ADDRS[0]}
        echo ${ADDRS[1]}
