apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: get-tags
spec:
  description: This task is for building image
  params:
    - name: image-name
      description: name of the image which needs to be created
      default: "sample-image"

  stepTemplate:
    env:
      - name: IMAGE_NAME
        value: $(params.image-name)

  steps:
    - name: test-build-image
      image: registry.access.redhat.com/ubi9/ubi
      script: |
        #!/bin/bash
        echo "Executing get-tags task"
