apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: is-commit-tag
spec:
  description: This task is for building image
  params:
    - name: image-name
      description: name of the image which needs to be created
      default: "sample-image"
  results:
    - name: is-commit-tag
      description: check git commit is tag
    - name: commit-short-sha
      description: first 8 character of commit sha

  stepTemplate:
    env:
      - name: IMAGE_NAME
        value: $(params.image-name)

  steps:
    - name: test-build-image
      image: registry.access.redhat.com/ubi9/ubi
      script: |
        #!/bin/bash
        echo "Executing is-commit-tag task"
        var="refs/tags/1.8"
        [[ "$var" =~ ^"refs/tags/" ]] && echo -n true > "$(results.is-commit-tag.path)" || echo -n false > "$(results.is-commit-tag.path)"
        echo "$(params.revision)" | head -c8 > "$(results.commit-short-sha.path)"
        echo "Find short tag"
        echo "$(tasks.is-commit-tag.results.commit-short-sha)"
